version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.30
    volumes:
      - ./sql-data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    hostname: technest
    environment:
      MYSQL_DATABASE: 'tn-accounts'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin1234'
      MYSQL_ROOT_PASSWORD: 'admin1234'